steps:
  # Paso 1: Instalar dependencias del proyecto
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Paso 2: Construir la aplicación de React
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

  # Paso 3: Desplegar a Firebase Hosting
  - name: 'gcr.io/cloud-builders/npm'
    args:
      - 'npx'
      - 'firebase-tools'
      - 'deploy'
      - '--only'
      - 'hosting'
      - '--project'
      - 'kamdata-sitioweb'