steps:
  # Paso 1: Instalar las dependencias
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Paso 2: Construir la aplicación de React
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

  # Paso 3: Desplegar a Cloud Storage
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gsutil'
    args:
      - '-m'
      - 'rsync'
      - '-c'
      - '-r'
      - 'build/.'
      - 'gs://www.kamdata.com.mx'

# ---- NUEVA SECCIÓN AL FINAL ----
options:
  logging: GCS_ONLY
  logsBucket: 'gs://kamdata-sitioweb-cloudbuild-logs'