steps:
  # Paso 1: Instalar dependencias
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install']

  # Paso 2: Construir la aplicación
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']

  # Paso 3: Desplegar a Firebase
  - name: 'node:18'
    entrypoint: 'npx'
    args:
      - 'firebase-tools'
      - 'deploy'
      - '--only'
      - 'hosting'
      - '--project'
      - 'kamdata-sitioweb-dd171' # <--- CAMBIO CLAVE

options:
  logging: CLOUD_LOGGING_ONLY