steps:
  # Paso 1: Obtener el token de despliegue desde Secret Manager
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - "gcloud secrets versions access latest --secret=firebase-deploy-token > /workspace/firebase_token.txt"

  # Paso 2: Instalar dependencias
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install']

  # Paso 3: Construir la aplicación
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']

  # Paso 4: Desplegar a Firebase usando el token
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - "npx firebase-tools deploy --only hosting --project kamdata-sitioweb --token \"$$(cat /workspace/firebase_token.txt)\""

options:
  logging: CLOUD_LOGGING_ONLY