steps:
  # Instala las dependencias del proyecto
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install']

  # Construye la aplicación de React
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']

  # Despliega en Firebase Hosting
  - name: 'node:18'
    entrypoint: 'npx'
    args:
      - 'firebase-tools'
      - 'deploy'
      - '--only'
      - 'hosting'
      - '--project'
      - 'kamdata-sitioweb' # <--- Apuntando al proyecto correcto

options:
  logging: CLOUD_LOGGING_ONLY