steps:
  # ... (los pasos 1 y 2 de npm no cambian) ...
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

  # Paso 3: Desplegar a Cloud Storage (CON EL AJUSTE)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gsutil'
    args:
      - '-m'
      - 'rsync'
      - '-a' # <---- AÑADE ESTA LÍNEA
      - 'public-read' # <---- Y ESTA LÍNEA
      - '-c'
      - '-r'
      - 'build/.'
      - 'gs://www.kamdata.com.mx'

options:
  logging: CLOUD_LOGGING_ONLY