# Netlify configuration for Kamdata Website

# Build settings
[build]
publish = "build"
command = "npm run build"

# Redirects for Single Page Application
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# Headers for security and performance
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
for = "/static/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.pdf"
[headers.values]
Content-Type = "application/pdf"
Cache-Control = "public, max-age=86400"